import React from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { 
  Hourglass, 
  Brain, 
  TrendingUp, 
  Mic,
  Star,
  CheckCircle
} from 'lucide-react'

export const Landing = () => {
  const { currentUser } = useAuth()

  const features = [
    {
      icon: Brain,
      title: 'AI-Driven Schedules',
      description: 'Personalized fasting plans generated by AI based on your unique biometrics and goals.'
    },
    {
      icon: TrendingUp,
      title: 'Adaptive Plans',
      description: 'Dynamic adjustments based on your daily check-ins and progress feedback.'
    },
    {
      icon: Hourglass,
      title: 'Smart Timer',
      description: 'Intuitive fasting timer with real-time progress tracking and motivating insights.'
    },
    {
      icon: Mic,
      title: 'Voice Journaling',
      description: 'Record your thoughts and feelings with automatic transcription and mood analysis.'
    }
  ]

  const benefits = [
    'Personalized fasting schedules',
    'AI-powered coaching',
    'Progress tracking & analytics',
    'Voice journaling with mood insights',
    'Adaptive plan adjustments',
    'Professional guidance'
  ]

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="text-center space-y-8">
            <div className="flex items-center justify-center space-x-3 mb-8">
              <Hourglass className="h-12 w-12 text-accent" />
              <h1 className="text-4xl md:text-6xl font-bold text-white">
                FastFlow
              </h1>
            </div>
            
            <p className="text-xl md:text-2xl text-white/80 max-w-3xl mx-auto">
              Your AI-powered intermittent fasting coach. Get personalized plans, track progress, 
              and optimize your health with intelligent guidance.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-12">
              {currentUser ? (
                <Link to="/dashboard">
                  <Button size="lg" className="w-full sm:w-auto">
                    Go to Dashboard
                  </Button>
                </Link>
              ) : (
                <>
                  <Link to="/auth">
                    <Button size="lg" className="w-full sm:w-auto">
                      Start Fasting
                    </Button>
                  </Link>
                  <Link to="/auth">
                    <Button variant="outline" size="lg" className="w-full sm:w-auto">
                      Sign In
                    </Button>
                  </Link>
                </>
              )}
            </div>

            {/* Demo Image Placeholder */}
            <div className="mt-16 relative">
              <Card variant="elevated" className="max-w-4xl mx-auto p-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                  <div className="space-y-6">
                    <div className="glass p-4 rounded-lg">
                      <h3 className="text-white font-semibold mb-2">Fasting Progress</h3>
                      <div className="text-2xl font-bold text-accent">12h 35m</div>
                      <div className="text-white/60">of 16h fast</div>
                    </div>
                    
                    <div className="glass p-4 rounded-lg">
                      <h3 className="text-white font-semibold mb-2">AI Coach</h3>
                      <div className="text-white/80">
                        "How are you feeling today?"
                      </div>
                    </div>
                  </div>
                  
                  <div className="space-y-4">
                    <div className="glass p-4 rounded-lg">
                      <h3 className="text-white font-semibold mb-2">Next Plan</h3>
                      <div className="text-white/80">
                        Your 16:8 schedule starts at 12:00 PM
                      </div>
                    </div>
                    
                    <div className="glass p-4 rounded-lg">
                      <h3 className="text-white font-semibold mb-2">Mood Trends</h3>
                      <div className="flex space-x-2">
                        {[...Array(5)].map((_, i) => (
                          <Star key={i} className="h-4 w-4 text-secondary fill-current" />
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Intelligent Fasting Made Simple
            </h2>
            <p className="text-xl text-white/70 max-w-2xl mx-auto">
              Advanced AI technology meets intuitive design to create the perfect fasting companion.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="text-center space-y-4">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/20">
                  <feature.icon className="h-8 w-8 text-primary" />
                </div>
                <h3 className="text-xl font-semibold text-white">{feature.title}</h3>
                <p className="text-white/70">{feature.description}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
                Everything You Need for Successful Fasting
              </h2>
              <p className="text-xl text-white/70 mb-8">
                FastFlow combines cutting-edge AI with proven fasting methodologies to help you achieve your health goals.
              </p>
              
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center space-x-3">
                    <CheckCircle className="h-6 w-6 text-secondary flex-shrink-0" />
                    <span className="text-white">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <Card variant="elevated" className="space-y-6">
              <h3 className="text-2xl font-bold text-white text-center mb-6">
                Ready to Transform Your Health?
              </h3>
              
              <div className="space-y-4">
                <div className="flex justify-between items-center py-3 border-b border-white/10">
                  <span className="text-white">Free Plan</span>
                  <span className="text-white font-semibold">$0/month</span>
                </div>
                <div className="flex justify-between items-center py-3 border-b border-white/10">
                  <span className="text-white">Pro Plan</span>
                  <span className="text-white font-semibold">$5/month</span>
                </div>
              </div>
              
              <div className="text-center pt-4">
                {!currentUser && (
                  <Link to="/auth">
                    <Button size="lg" className="w-full">
                      Start Your Journey
                    </Button>
                  </Link>
                )}
              </div>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}